### PR TITLE
Fix wording in README

### PR DESCRIPTION
**Pull request by AMartinNo1**

### CODE REVIEW

**Comment by helhum** [comment]
Thanks! The upload folder is gone though in TYPO3 10.4, so how about removing the whole paragraph? What do you think?

**Comment by AMartinNo1** [comment]
Happy to help!

Currently lower versions are according to composer.json (`"typo3/cms-core": "^8.7.10 || ^9.5.2 || ^10.4",`) supported. So I would not remove it. Max I would do is to add sth. like:

**Relevant for v8 / v9:**
Lorem ipsum.

**Comment by AMartinNo1** [comment]
@helhum Should I make a change with my suggestion on your idea or did you simply had no time yet to check my response?

**Comment by helhum** [comment]
Let's just get the typos fixed for now

**Pull request merged**
